apiVersion: v1
kind: Service
metadata:
  name: devops-ai-backend
  namespace: devops-ai
spec:
  selector:
    app: devops-ai-backend

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: devops-ai-frontend
  namespace: devops-ai
spec:
  selector:
    app: devops-ai-frontend

  ports:
    - port: 5173
      targetPort: 5173

  type: NodePort